version: "3.7"

services:

  webserver:
    image: ${AIRFLOW_DOCKER}
    volumes:
      - ./dags:${AIRFLOW_WORKSPACE}/dags
      - ./airflow.cfg:${AIRFLOW_WORKSPACE}/airflow.cfg
    environment:
      NODE_ROLE: scheduler
    command: ["airflow webserver -p 8080"]
    ports:
      - "8080:8080"
    networks:
      - airflow-demo-net

  scheduler:
    image: ${AIRFLOW_DOCKER}
    volumes:
      - ./dags:${AIRFLOW_WORKSPACE}/dags
      - ./airflow.cfg:${AIRFLOW_WORKSPACE}/airflow.cfg
    environment:
      NODE_ROLE: scheduler
    command: ["airflow scheduler"]
    networks:
      - airflow-demo-net

  flower:
    image: ${AIRFLOW_DOCKER}
    volumes:
      - ./airflow.cfg:${AIRFLOW_WORKSPACE}/airflow.cfg
    command: ["airflow flower"]
    ports:
      - "5555:5555"
    networks:
      - airflow-demo-net

  worker:
    image: ${AIRFLOW_DOCKER}
    volumes:
      - ./dags:${AIRFLOW_WORKSPACE}/dags
      - ./airflow.cfg:${AIRFLOW_WORKSPACE}/airflow.cfg
    command: ["airflow worker -c 1 -q queue_one"]
    networks:
      - airflow-demo-net
  worker2:
    image: ${AIRFLOW_DOCKER}
    volumes:
      - ./dags:${AIRFLOW_WORKSPACE}/dags
      - ./airflow.cfg:${AIRFLOW_WORKSPACE}/airflow.cfg
    command: ["airflow worker -c 1 -q queue_two"]
    networks:
      - airflow-demo-net

networks:
  airflow-demo-net:
    name: airflow-demo-net
    external: true